"""
core/security.py - Password hashing, JWT token utilities, and RBAC dependencies
"""
import hashlib
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from passlib.context import CryptContext
from sqlalchemy.orm import Session

from core.config import settings
from database import get_db

# ── Password hashing contexts ────────────────────────────────────────────────
_bcrypt_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
_bearer     = HTTPBearer(auto_error=False)


def hash_password(password: str) -> str:
    """Return a bcrypt hash of the given password."""
    return _bcrypt_ctx.hash(password)


def verify_password(plain: str, hashed: str) -> bool:
    """
    Verify *plain* against *hashed*.
    Supports both legacy SHA-256 hashes (for existing seeded data) and
    bcrypt hashes generated by hash_password().
    """
    if len(hashed) == 64 and all(c in "0123456789abcdef" for c in hashed):
        return hashlib.sha256(plain.encode()).hexdigest() == hashed
    try:
        return _bcrypt_ctx.verify(plain, hashed)
    except Exception:
        return False


# ── JWT tokens ───────────────────────────────────────────────────────────────

def create_access_token(
    data: dict,
    expires_delta: Optional[timedelta] = None,
) -> str:
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (
        expires_delta or timedelta(minutes=settings.access_token_expire_minutes)
    )
    to_encode["exp"] = expire
    return jwt.encode(to_encode, settings.secret_key, algorithm=settings.algorithm)


def decode_token(token: str) -> Optional[dict]:
    try:
        return jwt.decode(token, settings.secret_key, algorithms=[settings.algorithm])
    except JWTError:
        return None


def get_user_id_from_token(token: str) -> Optional[int]:
    payload = decode_token(token)
    return payload.get("user_id") if payload else None


def get_username_from_token(token: str) -> Optional[str]:
    payload = decode_token(token)
    return payload.get("sub") if payload else None


# ── RBAC FastAPI dependencies ─────────────────────────────────────────────────

def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
    db: Session = Depends(get_db),
) -> dict:
    """
    FastAPI dependency — extracts and verifies the Bearer JWT from the
    Authorization header.  Returns the decoded token payload dict on
    success, or raises HTTP 401.

    Usage:
        @router.get("/protected")
        def my_endpoint(user = Depends(get_current_user)):
            ...
    """
    _401 = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Not authenticated — valid Bearer token required",
        headers={"WWW-Authenticate": "Bearer"},
    )
    if not credentials:
        raise _401
    payload = decode_token(credentials.credentials)
    if not payload:
        raise _401
    return payload   # {"sub": username, "user_id": int, "role": str, "exp": ...}


def require_role(*allowed_roles: str):
    """
    FastAPI dependency factory for Role-Based Access Control.

    Usage:
        @router.get("/finance-only")
        def endpoint(user = Depends(require_role("FINANCE_MANAGER", "ADMIN"))):
            ...

    Raises HTTP 403 when the authenticated user's role is not in *allowed_roles*.
    """
    def _dependency(user: dict = Depends(get_current_user)) -> dict:
        role = (user.get("role") or "").upper()
        if role not in [r.upper() for r in allowed_roles]:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Access denied — required role(s): {', '.join(allowed_roles)}",
            )
        return user
    return _dependency


# ── Convenience role guards ─────────────────────────────────────────────────

def admin_only(user: dict = Depends(require_role("ADMIN"))) -> dict:
    return user

def finance_or_admin(user: dict = Depends(require_role("FINANCE_MANAGER", "ADMIN"))) -> dict:
    return user

def any_authenticated(user: dict = Depends(get_current_user)) -> dict:
    return user

